//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalsx4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PD_ID { get; set; }
        public string PD_Name { get; set; }
        public string PD_Description { get; set; }
        public string PD_Image { get; set; }
        public int PD_Price { get; set; }
    }
}
